#!/usr/bin/env bash
# Friendly installer for macOS/Linux - a UX wrapper around setup.py, not a
# reimplementation of it. All the actual provisioning logic (checking
# Docker, creating the venv, installing deps, generating judge0.conf,
# walking through Google credentials) lives in setup.py, which is plain
# Python and works identically on macOS/Windows/Linux. This script just
# gives that a nicer front door on Mac/Linux, and leaves behind two thin
# launcher scripts (start.sh/stop.sh) so day-to-day usage stays
# `./start.sh` / `./stop.sh` instead of typing `python3 start.py` every
# time - those launchers are two-line passthroughs, not duplicated logic,
# so there's nothing here that can drift out of sync with start.py/stop.py.
#
# Usage:
#   ./install.sh

set -uo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

BLUE='\033[1;34m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
RED='\033[0;31m'
DIM='\033[2m'
RESET='\033[0m'

banner() {
  echo -e "${BLUE}"
  echo "   ___    _                 _   _  __       "
  echo "  / _ \  (_)  ___   _ __   | |_ (_)/ _|  _   _ "
  echo " / /_\/  | | |_  |  | '_ \  | __|| || |_  | | | |"
  echo "/ /_\\   | |  / /  | | | | | |_ | ||  _| | |_| |"
  echo "\____/   |_| /___| |_| |_|  \__||_||_|    \__, |"
  echo "                                          |___/ "
  echo -e "${RESET}${DIM}Campus Test Console - installer${RESET}"
  echo
}

section() { echo -e "\n${CYAN}▸ $1${RESET}"; }
pass()    { echo -e "  ${GREEN}✓${RESET} $1"; }
fail()    { echo -e "  ${RED}✗${RESET} $1"; }

find_python() {
  if command -v python3 > /dev/null 2>&1; then
    echo "python3"
  elif command -v python > /dev/null 2>&1; then
    echo "python"
  else
    echo ""
  fi
}

banner

section "Checking for Python"
PYTHON_BIN="$(find_python)"
if [ -z "$PYTHON_BIN" ]; then
  fail "No python3/python found on PATH."
  echo "    Install Python 3.10+ from https://www.python.org/downloads/ and re-run ./install.sh"
  exit 1
fi
pass "Found $($PYTHON_BIN --version 2>&1) ($PYTHON_BIN)"

section "Running setup (Docker check, venv, dependencies, Judge0 config, Google credentials)"
if ! "$PYTHON_BIN" setup.py; then
  echo
  fail "Setup did not finish - see the messages above for what's missing, fix it, then re-run ./install.sh"
  exit 1
fi

section "Creating start.sh / stop.sh launchers"
cat > "$ROOT_DIR/start.sh" <<EOF
#!/usr/bin/env bash
# Thin launcher - all real logic lives in start.py. Regenerated by
# install.sh; safe to re-run install.sh any time, this file is disposable.
cd "\$(dirname "\${BASH_SOURCE[0]}")"
exec $PYTHON_BIN start.py "\$@"
EOF
chmod +x "$ROOT_DIR/start.sh"
pass "start.sh"

cat > "$ROOT_DIR/stop.sh" <<EOF
#!/usr/bin/env bash
# Thin launcher - all real logic lives in stop.py. Regenerated by
# install.sh; safe to re-run install.sh any time, this file is disposable.
cd "\$(dirname "\${BASH_SOURCE[0]}")"
exec $PYTHON_BIN stop.py "\$@"
EOF
chmod +x "$ROOT_DIR/stop.sh"
pass "stop.sh"

section "Starting the stack now"
"$PYTHON_BIN" start.py

VENV_PY="$ROOT_DIR/.venv/bin/python3"
LAN_IP="$("$PYTHON_BIN" -c 'from proc_utils import get_lan_ip; print(get_lan_ip() or "")' 2>/dev/null)"

echo
echo -e "${BLUE}================================================================${RESET}"
echo -e "${GREEN}Setup complete.${RESET}"
echo
echo -e "  Admin dashboard:   ${CYAN}http://127.0.0.1:8787${RESET}   (this machine only, by default)"
if [ -n "$LAN_IP" ]; then
  echo -e "  This machine's LAN IP: ${CYAN}$LAN_IP${RESET}  (used if you enable LAN access from Admin → Network access)"
fi
echo -e "  Judge0 (internal): ${DIM}http://127.0.0.1:2358${RESET}  (not for direct use)"
echo
if [ ! -f "$ROOT_DIR/credentials/client_secret.json" ]; then
  echo -e "  ${RED}Action needed:${RESET} Google credentials not set up yet - Aptitude/Programming/"
  echo "  Technical Discussion invites won't work until this is done. See SETUP.md step 3."
elif [ ! -f "$ROOT_DIR/credentials/token.json" ]; then
  echo -e "  ${RED}Action needed:${RESET} Google sign-in not completed yet - run:"
  echo "    $VENV_PY generate_refresh_token.py"
else
  echo -e "  ${GREEN}Google credentials:${RESET} configured."
fi
echo
echo "  Day to day:"
echo "    ./start.sh   - start the stack"
echo "    ./stop.sh    - stop it"
echo "    $VENV_PY app.py   - start a live candidate test session (separate, LAN-facing)"
echo -e "${BLUE}================================================================${RESET}"
